format = """
$directory$nodejs$golang $git_branch $rust
[⟫](bold green) """

scan_timeout = 10

[nodejs]
format = "[ at $version](green)"

[golang]
format = "[ﳑ at $version](cyan)"

[rust]
format = " at [$version](red bold)"

[git_branch]
symbol = " "
truncation_length = 10
truncation_symbol = ""
